# Generated by Django 4.0.6 on 2022-07-19 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Downvote',
            new_name='DownvotePost',
        ),
        migrations.RenameModel(
            old_name='Upvote',
            new_name='UpvotePost',
        ),
    ]
