# Generated by Django 4.0.6 on 2022-07-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_downvote_downvotepost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='user',
        ),
    ]
