version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: soc
      POSTGRES_DB: soc
      POSTGRESS_PASS: socpass
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5438:5432

  soc_media:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  pgdata: