# Generated by Django 4.0.6 on 2022-07-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivedmessage',
            old_name='user',
            new_name='to_user',
        ),
        migrations.RenameField(
            model_name='sentmessage',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RemoveField(
            model_name='receivedmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='received_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chating.receivedmessage'),
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
